#theme: jekyll-theme-hydejack

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - test

#webaddress: "https://mcmd.github.io/testGithubPages"
#url: "https://mcmd.github.io/testGithubPages"

remote_theme: broccolini/athena
#broccolini/swiss 
#mistakes/minimal-mistakes

#broccolini/swiss 
#qwtel/hydejack

minima:
  skin: dark

site:
  author: 
    name: John Smith
    email: "john.smith@foobar.com"
