#theme: minima

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - test

plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima

minima:
  skin: solarized

site:
  author: John Smith
  email: "john.smith@foobar.com"
